name: Build rk3588 kernel 6.x for rockchip linux

on:
  # schedule:
  #   - cron: "0 22 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

run-name: Build rk3588 kernel with rockchip linux

jobs:
  kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
            - jammy
            - noble
            - oracular

    name: Build kernel 

    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
            qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
            debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
            udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
            python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
            python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools
          sudo sudo apt-get install -y libelf-dev pahole

      - name: Build kernel
        shell: bash
        run: |
          rm -rf *
          git clone https://github.com/Joshua-Riek/ubuntu-rockchip --depth 1
          mv ubuntu-rockchip/* .
          sudo ./build.sh --board=orangepi-5-plus --suite ${{ matrix.suite }} --flavor desktop --kernel-only

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: jammy-orangepi-5-plus-kernel-${{ matrix.suite }}
          path: ./build/*.deb
          if-no-files-found: error

      - name: Upload Kernel to release
        uses: ncipollo/release-action@main
        with:
          tag: latest
          artifacts: ./build/*.deb
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            The kernel for rk3588 sbc, eg orangepi-5-plus.
