name: Build rk3588 5.x/6.x kernel for rockchip linux

on:
  # schedule:
  #   - cron: "0 22 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

run-name: Build rk3588 5.x/6.x kernel with rockchip linux

jobs:
  kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
            - jammy
            - noble
            - oracular

    name: Build kernel 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
            qemu-user-static qemu-system-arm u-boot-tools binfmt-support \
            debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
            udev dosfstools uuid-runtime git-lfs device-tree-compiler python3 fdisk \
            bc debhelper python3-pyelftools python3-setuptools dctrl-tools libelf-dev \
            python3-pkg-resources swig libfdt-dev libpython3-dev pahole

      - name: Build kernel
        shell: bash
        run: |
          rm -rf *
          git clone https://github.com/Joshua-Riek/ubuntu-rockchip --depth 1
          mv ubuntu-rockchip/* .
          mkdir -p build/
          pushd build
          git clone https://github.com/Joshua-Riek/linux-rockchip -b ${{ matrix.suite }}  --depth 1
          wget https://raw.githubusercontent.com/feicong/linux-rockchip/refs/heads/${{ matrix.suite }}/debian.rockchip/config/config.common.ubuntu
          mv config.common.ubuntu linux-rockchip/debian.rockchip/config/
          popd
          sudo ./build.sh --board=orangepi-5-plus --suite ${{ matrix.suite }} --flavor desktop --kernel-only

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ubuntu-kernel-${{ matrix.suite }}
          path: ./build/*.deb
          if-no-files-found: error

      - name: Upload Kernel to release
        uses: ncipollo/release-action@main
        with:
          tag: latest
          artifacts: ./build/*.deb
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            The kernel enable all eBPF features for rk3588 sbc, eg orangepi-5-plus.

            https://github.com/feicong/ebpf-course

            linux-*5.10.*.deb -> jammy
            linux-*6.1.*.deb -> noble
            linux-*6.11.*.deb -> oracular
            
